import  com.example.myhome.domain.*;
rule "3"
    when
        dto : DroolsDTO( deviceType=="door3" && (value >= 20.0  || value <=11.0));
    then
        dto.setAlarm(true);
end;
rule "1"
    when
        dto : DroolsDTO( deviceType=="door1" && (value >= 12.0  || value <=3.0));
    then
        dto.setAlarm(true);
end;
rule "4"
    when
        dto : DroolsDTO( deviceType=="refrigerator1" && (value >= 12.0  || value <=3.0));
    then
        dto.setAlarm(true);
end;
rule "7"
    when
        dto : DroolsDTO( deviceType=="doorlock1" && (value >= 5.0  || value <=3.0));
    then
        dto.setAlarm(true);
end;
