import  com.example.myhome.domain.DroolsDTO;

rule "Rule for door"
    when
        dto : DroolsDTO( deviceType=="DOOR" && value >= 10 );
    then
        dto.setAlarm(true);
end;

rule "Rule for refrigerator"
    when
        dto : DroolsDTO( deviceType=="REFRIGERATOR" && value >= 10 );
    then
        dto.setAlarm(true);
end;

rule "Rule for doorlock"
    when
        dto : DroolsDTO( deviceType=="DOORLOCK" && value >= 3 );
    then
        dto.setAlarm(true);
end;

rule "Rule for air conditioner"
    when
        dto : DroolsDTO( deviceType=="AIR_CONDITIONER" && value <= 10 );
    then
        dto.setAlarm(true);
end;

rule "Rule for dishwasher"
    when
        dto : DroolsDTO( deviceType=="DISHWASHER" && value >= 50 );
    then
        dto.setAlarm(true);
end;